### ISSUE TITLE
Jackets disappeared

### ISSUE THREAD

**Issue by bhardin** [din/simplify_jackets#1]
I was attempting to create a jacket and following the steps to watch the jackets folder for changes. Now, no jackets work. Is there a way to reset simplify?

**Comment by din** [comment]
You can fully remove Simplify's preferences using the following command: `rm -rf ~/Library/Containers/pixelmates.Simplify/Data/Library/Preferences/pixelmates.Simplify.*`

But it shouldn't behave like that. I need somehow to reproduce your issue. Can you help?

**Comment by bhardin** [comment]
I don't know. There were many factors. I was playing with a bunch of stuff. When I got to the office it resolved itself. Maybe internet connection?
