### ISSUE TITLE
Retina problems with retrosimplify and others

### ISSUE THREAD

**Issue by LATBauerdick** [din/simplify_jackets#3]
Hi -- I noticed that for HiDPI displays and I believe also retina the retrosimplify jacket and also the Jewel Case does not correctly display the cover art. 

Fir Retrosimplify a fix is to add a 

```
        $(".cover").css("background-size", "cover");
```

after setting the new image URL. For reasons I don't understand putting the background-size attribute into the .css file doesn't help. 

Best regards, LatB

**Comment by din** [comment]
Hello,

They changed handling of 'background-size' in Safari, so we need either set it from JS or fix somehow via CSS. We already fixed it, but Apple still haven't reviewed our app to push it to the App Store with all the fixes.
